# Generated by Django 3.0.5 on 2020-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200403_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
    ]
