# Generated by Django 3.0.5 on 2020-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200412_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(blank=True, default='https://images.app.goo.gl/AJNGPj9wRoAcea5x6', null=True, upload_to=''),
        ),
    ]
