# Generated by Django 3.0.5 on 2020-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20200412_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(blank=True, default='https://images.app.goo.gl/xm5KqFoKirbe5HS39', null=True, upload_to=''),
        ),
    ]
