# Generated by Django 3.0.5 on 2020-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20200413_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='thumb',
        ),
    ]
