# Generated by Django 3.0.5 on 2020-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_remove_articles_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
